// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXlnqLGcAsl0Wj2dowTuY0HgpljddI0SQ',
    appId: '1:550158911763:web:b05e37428c1d7f2959f2e6',
    messagingSenderId: '550158911763',
    projectId: 'flutter-auth-cb30c',
    authDomain: 'flutter-auth-cb30c.firebaseapp.com',
    storageBucket: 'flutter-auth-cb30c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfjgsd1Vhw-6GQPNaAnUn8tmngNiNmpbo',
    appId: '1:550158911763:android:8982fe6789a3727b59f2e6',
    messagingSenderId: '550158911763',
    projectId: 'flutter-auth-cb30c',
    storageBucket: 'flutter-auth-cb30c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkGHBdGnv4kfAwze3rlZ4jTu8vCNQM180',
    appId: '1:550158911763:ios:efcd1a64edd789e259f2e6',
    messagingSenderId: '550158911763',
    projectId: 'flutter-auth-cb30c',
    storageBucket: 'flutter-auth-cb30c.appspot.com',
    iosClientId: '550158911763-bkrjmmu4kpsbbdgt5miihaddjeb9g2ou.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkGHBdGnv4kfAwze3rlZ4jTu8vCNQM180',
    appId: '1:550158911763:ios:efcd1a64edd789e259f2e6',
    messagingSenderId: '550158911763',
    projectId: 'flutter-auth-cb30c',
    storageBucket: 'flutter-auth-cb30c.appspot.com',
    iosClientId: '550158911763-bkrjmmu4kpsbbdgt5miihaddjeb9g2ou.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginAuth',
  );
}
